<html>
<head>
<script type="text/javascript">

function log(message)
{
    document.getElementById('console').appendChild(document.createTextNode(message + "\n"));
}

if (window.testRunner) {
    testRunner.dumpAsText();
    testRunner.waitUntilDone();
}

function stopTest() {
    if (window.testRunner)
        testRunner.notifyDone();
}

function runTest() {
    try {
        var xhr = new XMLHttpRequest;
        xhr.open("PUT", "http://localhost:8000/xmlhttprequest/resources/basic-auth/access-control-auth-basic.php?uid=fooUser", true, "fooUser", "barPass");
        xhr.withCredentials = true;
        xhr.onerror = function (e) {
            log("FAILED: received error");
            stopTest();
        };
        xhr.onreadystatechange = function () {
            if (xhr.readyState == 4) {
                log((xhr.status == 401) ? "PASSED" : "FAILED: credential send!");
                stopTest();
            }
        };
        xhr.send();
    } catch(e) {
        log("FAILED: got exception " + e.message);
    }
}

</script>
</head>
<body onload="runTest();">
<p>Test case for bug <a href="https://bugs.webkit.org/show_bug.cgi?id=37781">37781</a>: [XHR] Cross-Origin asynchronous request with credential raises NETWORK_ERR</p>
<pre id='console'></pre>
</body>
</html>
